# Generated by Django 3.0.2 on 2020-01-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DukeDidi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='sharers',
            field=models.ManyToManyField(blank=True, related_name='ride_sharers_set', to='DukeDidi.User'),
        ),
    ]
