# Generated by Django 3.0.2 on 2020-01-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DukeDidi', '0006_auto_20200130_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrive_time',
            field=models.DateTimeField(null=True),
        ),
    ]
