# Generated by Django 3.0.2 on 2020-02-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DukeDidi', '0009_ride_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sharer_party_size',
            field=models.IntegerField(default=0),
        ),
    ]
