# Generated by Django 3.0.2 on 2020-02-02 05:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DukeDidi', '0010_user_sharer_party_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='sharers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=100, null=True), default=list, size=None),
        ),
    ]
