# Generated by Django 3.0.2 on 2020-02-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DukeDidi', '0011_auto_20200202_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='sharer_partysize_pair',
            field=models.TextField(blank=True, null=True),
        ),
    ]
