# Generated by Django 3.0.2 on 2020-01-31 02:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DukeDidi', '0005_auto_20200130_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rides_arr',
        ),
        migrations.AlterField(
            model_name='ride',
            name='sharers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=100, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
