# Generated by Django 3.0.2 on 2020-01-31 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DukeDidi', '0007_auto_20200130_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='arrive_time',
            new_name='arrival_time',
        ),
    ]
