# Generated by Django 3.0.2 on 2020-02-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DukeDidi', '0008_auto_20200130_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
