# Generated by Django 3.0.2 on 2020-02-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DukeDidi', '0012_ride_sharer_partysize_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='license_plate_number',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
